import { createProfile, getProfileByUserId } from "@/db/queries/profiles-queries";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth()

  if (userId) {
    const profile = await getProfileByUserId(userId)
    if (!profile) {
      await createProfile({ userId })
    }
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${GeistSans.className} ${GeistMono.className} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}